
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"; 
import AuthProvider from "@/lib/AuthProvider";


export const metadata: Metadata = {
  title: "TELEGRAM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background antialiased transition-colors duration-300">
        <AuthProvider>
        <ThemeProvider
          attribute="class" 
          defaultTheme="system" 
          enableSystem 
          disableTransitionOnChange={false}
          
          >
          {children}
        </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}